// Code generated by gen_pb (hand-generated due to missing protoc). DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: hint/proxy/shadowtls/config.proto

package shadowtls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server address in "host:port" format
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Password
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Protocol version: 1, 2 or 3 (default 3)
	Version int32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// TLS SNI override (defaults to the server host)
	Sni string `protobuf:"bytes,4,opt,name=sni,proto3" json:"sni,omitempty"`
	// Skip certificate verification
	Insecure      bool `protobuf:"varint,5,opt,name=insecure,proto3" json:"insecure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_hint_proxy_shadowtls_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_hint_proxy_shadowtls_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_hint_proxy_shadowtls_config_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ClientConfig) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *ClientConfig) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

var File_hint_proxy_shadowtls_config_proto protoreflect.FileDescriptor

var file_hint_proxy_shadowtls_config_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x68, 0x69, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x73, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x74, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x76, 0x32, 0x72, 0x61, 0x79, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x74, 0x6c, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x0c,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x6e, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6e, 0x69, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x32, 0x72, 0x61, 0x79, 0x41, 0x2f,
	0x76, 0x32, 0x72, 0x61, 0x79, 0x61, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x68, 0x69, 0x6e, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x74, 0x6c, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_hint_proxy_shadowtls_config_proto_rawDescOnce sync.Once
	file_hint_proxy_shadowtls_config_proto_rawDescData []byte
)

func file_hint_proxy_shadowtls_config_proto_rawDescGZIP() []byte {
	file_hint_proxy_shadowtls_config_proto_rawDescOnce.Do(func() {
		file_hint_proxy_shadowtls_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hint_proxy_shadowtls_config_proto_rawDesc), len(file_hint_proxy_shadowtls_config_proto_rawDesc)))
	})
	return file_hint_proxy_shadowtls_config_proto_rawDescData
}

var file_hint_proxy_shadowtls_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hint_proxy_shadowtls_config_proto_goTypes = []any{
	(*ClientConfig)(nil), // 0: v2raya.proxy.shadowtls.ClientConfig
}
var file_hint_proxy_shadowtls_config_proto_depIdxs = []int32{
	0, // 0: v2raya.proxy.shadowtls.ClientConfig
}

func init() { file_hint_proxy_shadowtls_config_proto_init() }
func file_hint_proxy_shadowtls_config_proto_init() {
	if File_hint_proxy_shadowtls_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hint_proxy_shadowtls_config_proto_rawDesc), len(file_hint_proxy_shadowtls_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hint_proxy_shadowtls_config_proto_goTypes,
		DependencyIndexes: file_hint_proxy_shadowtls_config_proto_depIdxs,
		MessageInfos:      file_hint_proxy_shadowtls_config_proto_msgTypes,
	}.Build()
	File_hint_proxy_shadowtls_config_proto = out.File
	file_hint_proxy_shadowtls_config_proto_goTypes = nil
	file_hint_proxy_shadowtls_config_proto_depIdxs = nil
}
